name: rate_my_app
description: Allows to kindly ask users to rate your app if custom conditions are met (eg. install time, number of launches, etc...).
version: 0.6.1+2
homepage: https://github.com/Skyost/RateMyApp

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  shared_preferences: ^2.0.6
  smooth_star_rating: ^1.1.0
  pedantic: '>=1.8.0 <2.0.0'
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.rate_my_app
        pluginClass: RateMyAppPlugin
      ios:
        pluginClass: RateMyAppPlugin
